---
core:
  ADMINUSER: admin
  AGUADIR: .flow 
  AGUAUSER: agua
  INSTALLDIR: /Users/kbsf633/localrepos/flow
  USERDIR: /home
database:
  DBFILE: db/flow.sqlite
  DBTYPE: SQLite
  TESTDBFILE: db/test.sqlite
  TESTDBTYPE: SQLite
